### ISSUE TITLE
querying information about a bug gives internal server error

### ISSUE THREAD

**Issue by KaratekHD** [KaratekHD/defrag#48]
**Steps to reproduce**
1. Start up defrag
2. Point your browser to http://localhost:8000/bugs/bug/1175535

**Expected behavior**
Information about the bug is displayed.

**Actual behavior**
The following returns:
```json
{
  "query": {
    "service": "bugs",
    "item_key": 1175535
  },
  "results_count": null,
  "results": null,
  "error": "A likely programming error occurred: This container type does not support __getitem__: <class 'pottery.dict.RedisDict'>"
}
```
**Detailed information**
In order to get more detailed information about what exactly goes wrong, we need to the `query` function in the `Run` class in 
[defrag/modules/helpers/services_manager.py](https://github.com/openSUSE/defrag-api/blob/dc404959c16c869edc42e32efc221d62e5c9dcab/defrag/modules/helpers/services_manager.py#L220) so that it looks like this:
```python
    @staticmethod
    async def query(query: CacheQuery, fallback: Optional[partial] = None) -> QueryResponse:
        """ Tries to run the given query, doing all the caching work along the way. A 'finally' clause might
        be in order. """
        if not ServicesManager.services:
            raise QueryException(
                "Services need to be initialized before running a query.")
        try:
            async with Run.Cache(query, fallback) as results:
                return QueryResponse(query=query, results=results, results_count=len(results))
        except QueryException as err:
            return QueryResponse(query=query, error=f"Unable to satisfy this query for this reason: {err}")
        except Exception as err:
            raise err # This line here changed
            return QueryResponse(query=query, error=f"A likely programming error occurred: {err}")

```
Doing so will give us the following stacktrace:
```
INFO:     127.0.0.1:56334 - "GET /bugs/bug/1175535 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 371, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/fastapi/routing.py", line 216, in app
    raw_response = await run_endpoint_function(
  File "/home/jens/src/defrag-api/ven/lib64/python3.8/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/jens/src/defrag-api/defrag/modules/bugs.py", line 166, in get_bug
    return await Run.query(cache_query, fallback)
  File "/home/jens/src/defrag-api/defrag/modules/helpers/services_manager.py", line 217, in query
    raise err
  File "/home/jens/src/defrag-api/defrag/modules/helpers/services_manager.py", line 212, in query
    async with Run.Cache(query, fallback) as results:
  File "/home/jens/src/defrag-api/defrag/modules/helpers/services_manager.py", line 189, in __aenter__
    if items_from_cache := await self.cache.search_items(item_key=self.query.item_key):
  File "/home/jens/src/defrag-api/defrag/modules/helpers/sync_utils.py", line 42, in inner
    return await loop.run_in_executor(None, f_saturated)
  File "/usr/lib64/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jens/src/defrag-api/defrag/modules/helpers/cache_stores.py", line 54, in search_items
    raise Exception(
Exception: This container type does not support __getitem__: <class 'pottery.dict.RedisDict'>
```

**Comment by why-not-try-calmer** [comment]
Hello, thanks for this Issue! I was a bit alarmed because you Telegram message said "can't fix myself" but I think you have correctly identified a problem.
Should I just make the change?

**Comment by KaratekHD** [comment]
Yes please!
